### PR TITLE
Linting

### PR DESCRIPTION
**Pull request by area**
This PR hopefully makes Bithound much closer to happy, and nothing else...

### CODE REVIEW

**Comment by area** [comment]
Really want to get some tests for what's in `runCoveredTests.js` before I do anything major in there, so probably going to draw inspiration from #18 next.

**Comment by cgewecke** [comment]
Yes, please feel free to just grab anything useful in #18. I have a PR with tests for conditionals I'll open tonight but it has a few line changes in instSolidity. If you merge this lint I can put everything in a branch based on the new master and hopefully it won't conflict.

**Comment by cgewecke** [comment]
Edit - I'm just going to branch off this.

**Comment by cgewecke** [comment]
Actually no, you can't review the changed lines in the PR because every line changed. I'm just going wait to open.

**Pull request merged**
