### PR TITLE
Working inside travis & support inheritance

### PR DESCRIPTION
**Pull request by adria0**
This PR fixes two issues:
+ Executing inside travis, the process does not hangs
+ Inheritance is now supported in contracts ( e.g. MyContract is Ownable ... )

### CODE REVIEW

**Comment by cgewecke** [comment]
@adriamb This is a great solution! I hope you don't mind - I merged it into a branch that's under development (truffle3) that has unit test fixtures for the cli to verify that it works and also ran it against some other truffle projects. It's seemed like everything was good. Did you have issues with this approach - is that why you closed?

**Comment by adria0** [comment]
This approach is now working nice. I closed the PR because I was trying to
do it over the master and Travis and there are some checks that failed (
solc version ). Next PRs I'll do them on Truffle3 branch :)

On Apr 19, 2017 7:11 PM, "c-g-e-w-e-k-e-&gt;" <notifications@github.com>
wrote:

@adriamb <https://github.com/adriamb> This is a great solution! I hope you
don't mind - I merged it into a branch that's under development (truffle3)
that has unit test fixtures for the cli to verify that it works and also
ran it against some other truffle projects. It's seemed like everything was
good. Did you have issues with this approach - is that why you closed?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/JoinColony/solcover/pull/57#issuecomment-295349668>,
or mute
the thread

**Comment by area** [comment]
This is a very neat solution, and I agree this is certainly good enough for almost all use cases, but I don't believe it puts it totally to bed. I think you can still make contracts that can't be compiled in solc 0.4.8 after instrumentation using the syntax:

```
import {Ownable as someName} from "Ownable.sol";

contract Ownable is someName {

}
```

It seems pretty unlikely that anyone would be using this pattern, as it'd make debugging even harder than usual, but I reckon it's technically valid! This is a moot point once truffle finally upgrades though, so it's probably a case of good enough 👍

**Comment by adria0** [comment]
I also made a modification to not to include the coverage of some helper contracts I have in the contracts folder. I think this feature could be usefull in the future.

There's any roadmap for solcover? I think community NEEDS those tools... the community needs to create nice contracts to prevent future OMGs...

**Pull request closed without merging**
