### PR TITLE
Truffle3

### PR DESCRIPTION
**Pull request by cgewecke**
@area this PR is an egregious breach of the 'small PR with clean commit records' rule, so I'm just going to throw it over the fence and run away.

PR resolves a number of issues raised over the last few months:
+ #59 - inline assembly parsing (fixed by adding relevant AST types to the list in `parse.js`)
+ #60 - instrumentation breaks function call chaining (see issue)
+ #61 - crashes on empty contract bodies (see issue)
+ #51 - solc 0.4.8 - integrates adriamb's fix for the inheritance problem. You identified a caveat there. It also had a very small issue with `LibraryStatements` that's fixed and otherwise seems to work perfectly.
+ #53 - solidity tests - this branch can be installed in the Truffle Metacoin project, run without configuration, have all of truffle's test pass and generate the reports without errors. Metacoin has solidity tests so maybe they won't require any special handling? Not sure.

PR makes structural changes to `runCoveredTests.js` (renamed `exec.js` for brevity). 
+ Target project (contracts, migrations, tests) - gets copied into a folder, instrumented and the tests run there. 
+ Patching is replaced with forks of testrpc, ethereumjs-vm, and provider-engine. This is done to make `npm install --save-dev solcover ` possible. There are no guarantees that the target doesn't already include these dependencies and forking them seems to be the simplest way of scoping the assets correctly and making sure Solcover's modifications don't affect the other packages. Have added you with full admin privileges to [a github org](https://github.com/sc-forks) created to  house them. You could fork them to Colony too though. The `ethereumjs-vm` there contains the patch you wrote and `testrpc` has been altered to have a higher default transaction gas because it looked like some transactions were running out of gas.
+ Istanbul is loaded using `require` - again this lets npm figure out where it is / resolves problems raised if it's already one of the target's dependencies.
+ Adds support for `--network coverage` (see [README.md](https://github.com/JoinColony/solcover/tree/truffle3))
+ Adds support for a small set of options loaded from a `.solcover.js` config file - basically testrpc options and an arbitrary test command (see [README.md](https://github.com/JoinColony/solcover/tree/truffle3))
+ Adds unit tests / unit test fixtures for `exec.js`.

PR edits README with new instructions and adds links to some example repos/reports (haven't asked any of those people for permission to be exemplified - probably bad because their tests have coverage gaps, they might be saddened by this discovery, etc.)

One test file with an intentional syntax error isn't passing the Lint CI. I've added that to an eslintignore file to no avail. Additionally, two of the tests in the `cli` suite are explicitly disabled in the CI context because they launch their own testrpc instances and max out CI's container memory limit. They run locally though. 

The case I'd make for building off this branch is that it goes some way towards addressing `runCoveredTests` usability issues. It installs and runs conventionally and cleans up on failure with clear-ish messages about the error source, so it's easier to test Solcover on real projects. 

By way of example: I ran it yesterday on [ChronoBank's (large) contract repo](https://github.com/ChronoBank/SmartContracts/tree/master/contracts) and was able to produce [this report]( https://sc-forks.github.io/SmartContracts/). Their 180+ test suite completed (with 6 failing 'events' tests) and the project only required a [small tweak to a test fixture method](https://github.com/sc-forks/SmartContracts/blob/master/test/helpers/eventsHelper.js#L46) because it crashed mocha on test failure. The mocha issue was clear from Solcover's error reporting. Other than that it required no special configuration and 'just worked.' 

Congratulations on publishing the beta. Awesome.

### CODE REVIEW

**Comment by maurelian** [comment]
So, I'm curious why this was closed? 

I love the changes here, and had much less trouble implementing it (the only issues were with a non-standard truffle folder configuration).

**Comment by cgewecke** [comment]
Hi @maurelian I closed it and moved these changes into a free standing fork of Solcover at [solidity-coverage](https://github.com/sc-forks/solidity-coverage) and am continuing development over there for the time being.

**Comment by area** [comment]
Ah, I'd been wondering the same - I didn't realise you'd forked it! I'd actually been running this branch against our contracts, and fixing a few issues that cropped up so I could merge it in (it's why I've been investigating https://github.com/ethereumjs/testrpc/issues/149). Not sure how you'd like to proceed? :smile:

**Comment by cgewecke** [comment]
Oh I'm sorry - it happened without that much thought - I wanted to install it on the Zeppelin contracts and they wanted it packaged as an npm dep. They're the only people who've installed it - but it works nicely - coveralls comments on the PRs etc. 

Obviously the project belongs here - I'd just like to be able keep pushing it forward. And there are things I'd really like to get done: 

+ filter Solcover events from the logs in testrpc so that events tests pass. 
+ be able to generate coverage for pythereum based projects like Gnosis
+ change the parser, again :) to [this antlr parser](https://github.com/federicobond/solidity-parser-antlr)
+ push to get it installed on as many major projects as possible

I'm happy to deprecate `sc-forks` and continue as before as long as it's not too much work for you to review everything etc. You have a full plate so . . .

Another possibility is to continue work on it over there - you have full admin rights there and should be able to push directly to master on any of those repos. It could come back when it's done and ready for release, which could be soon. 

What are your views? What would you like to see happen? This is your code - I'm happy to do whatever you think is best.

**Comment by maurelian** [comment]
Sorry to interject, but maybe just make @cgewecke a `contributor` on this repo? Sounds like it's the commit privs that drove him to fork.

**Pull request closed without merging**
