### PR TITLE
Istanbul tests, fix If bug (#26), support loop statements (#27)

### LINKED ISSUE #26: Unbracketed If consequents / alternates not getting statement or line coverage
```javascript
if (x ==1 ) throw;
```
gets covered as:
```javascript
StatementCoverage('test.sol',1);
if (x == 1) {BranchCoverage('test.sol',1,0);throw;}else { BranchCoverage('test.sol',1,1);}
```
It should be the same as the bracketed version `if(x==1){throw;}`:
```javascript
StatementCoverage('test.sol',1);
if (x == 1) {BranchCoverage('test.sol',1,0);  StatementCoverage('test.sol',2);
throw; }else { BranchCoverage('test.sol',1,1);}
```

Ditto
```
if (x == 1 )
  y = 2;
```
currently covered as:
```javascript
StatementCoverage('test.sol',1);
if (x == 1) 
            {BranchCoverage('test.sol',1,0);throw;}else { BranchCoverage('test.sol',1,1);}
```
When the consequent is bracketed it gets statement and line coverage:
```javascript
StatementCoverage('test.sol',1);
if (x == 1){BranchCoverage('test.sol',1,0); 
Coverage('test.sol',6);
             StatementCoverage('test.sol',2);
throw;
        }else { BranchCoverage('test.sol',1,1);}
```

Submitting a PR for this later today.

### PR DESCRIPTION
**Pull request by cgewecke**
(I accidentally merged my dev branch into the original PR #29 - this is a resubmission of the same)
This PR:

+ Adds some utilities to implement #13 per @area's design and algorithm. 
+ Converts `if` compilation tests to coverage correctness tests.
+ Adds support  for `for` and `while` statements.
+ Adds tests for `for` and `while` statement coverage correctness
+ Adds a utility that fixes #26 by preprocessing all contracts so that unbracketed singleton statements associated with if, else, for, and while loops are bracketed before solcover parses them.
+ Removes logic in `instrumentIfStatement` that manages unbracketed consequents and alternates (preprocessor ensures they don't occur).
+ Allows lines with form `{ <statement>; }` to be instrumented as lines. (This is part of the #26 fix - the preprocessor blocks lines like that.)

### CODE REVIEW

**Comment by area** [comment]
This is a great PR. I love how pared down the tests are now that test if coverage is what we expect it to be!

There are a couple of issues I'd like resolved before merging though. The first is to get `runCoveredTests.js` using `coverageMap.js`:

```
var Web3 = require('web3');
var web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"));

var shell = require('shelljs');
var SolidityCoder = require("web3/lib/solidity/coder.js");
var fs = require('fs');
var path = require('path');
var getInstrumentedVersion = require('./instrumentSolidity.js');
var CoverageMap = require('./coverageMap.js');
var coverage = new CoverageMap();

var childprocess = require('child_process');

//PAtch our local testrpc if necessary
if (!shell.test('-e','./node_modules/ethereumjs-vm/lib/opFns.js.orig')){
    console.log('patch local testrpc...')
    shell.exec('patch -b ./node_modules/ethereumjs-vm/lib/opFns.js ./hookIntoEvents.patch')
}
//Run the modified testrpc with large block limit
var testrpcProcess = childprocess.exec('./node_modules/ethereumjs-testrpc/bin/testrpc --gasLimit 0xfffffffffff')

if (shell.test('-d','../originalContracts')){
    console.log("There is already an 'originalContracts' directory in your truffle directory.\nThis is probably due to a previous solcover failure.\nPlease make sure the ./contracts/ directory contains your contracts (perhaps by copying them from originalContracts), and then delete the originalContracts directory.")
    process.exit(1);
}

shell.mv('./../contracts/', './../originalContracts/');
shell.mkdir('./../contracts/');
//For each contract in originalContracts, get the instrumented version
shell.ls('./../originalContracts/*.sol').forEach(function(file) {
    if (file !== 'originalContracts/Migrations.sol') {
        console.log("instrumenting ", file);
        var contract = fs.readFileSync("./" + file).toString();
        var fileName = path.basename(file);
        var instrumentedContractInfo = getInstrumentedVersion(contract, fileName, true);
        fs.writeFileSync('./../contracts/' + path.basename(file), instrumentedContractInfo.contract);
        var canonicalContractPath = path.resolve('./../originalContracts/' + path.basename(file));
        coverage.addContract(instrumentedContractInfo, canonicalContractPath);
    }
});
shell.cp("./../originalContracts/Migrations.sol", "./../contracts/Migrations.sol");

shell.rm('./allFiredEvents'); //Delete previous results
shell.exec('truffle test --network coverage');

events = fs.readFileSync('./allFiredEvents').toString().split('\n')
events.pop();
//The pop here isn't a bug - there is an empty line at the end of this file, so we
//don't want to include it as an event.
coverage.generate(events, './../originalContracts/');

fs.writeFileSync('./coverage.json', JSON.stringify(coverage.coverage));

shell.exec("./node_modules/istanbul/lib/cli.js report html")
testrpcProcess.kill();
shell.rm('-rf', './../contracts');
shell.mv('./../originalContracts', './../contracts');
```

The second issue is a little more subtle; the preprocessor messes up highlighting by introducing extra characters... I think a solution to this is to parse it without the preprocessor to get the map, run the preprocessor, and then only inject the instrumentation to the source once the map is obtained.

syntax highlighting

**Comment by area** [comment]
I've also added you as a collaborator so future branches you make can be inside this repo, which will make collaborating on PRs like this easier 👍

**Comment by cgewecke** [comment]
Thanks so much for adding me as collaborator!  

RE: integrating coverage map with runCoveredTests - maybe the way to proceed is to close this and re-open it as a JoinColony branch so that you can add those changes (plus the nested contract directory handling from #28)? Those two seem to fit together. 

RE: syntax highlighting. Good catch and extremely vexing! Initially I tried the approach you suggest and simply could not find a way to get the statement and line coverage events inside the brackets of the branch coverage event. Do you have an idea of how to solve this? It seems like it might require defining a new path specifically for these singleton cases as the map is traversed across `parse['ifStatement']`, `instrumentIfStatement`, `instrumentStatement`, and `instrumentLine`. So . . . you don't insert the branch coverage event until you've extracted the column data and checked the line? Sorry if that's gibberish, I find this problem really confusing. 

Some ways forward from that are:
+ open a branch that just has failing tests and the test utilities - leaves instrumentSolidity.js intact - and work on a solution for #26 that doesn't have the syntax highlighting defect.
+ open a branch that accepts #30 as a temporary solution for the if and loop statement problems and open the syntax highlighting as a separate issue that can be fixed when a good solution is found for it. 

Either is fine with me. Or any other way fine too lol. Menu of choices here - just let me know what's best.

**Comment by area** [comment]
Ah yeah, it's not quite as simple as I thought. I'm almost inclined to let it slide for now - it improves the codebase, and the syntax highlighting is very close to right, so it doesn't impact practical usability, it just causes a minor annoyance!

I'll give it some more thought, but I imagine I'll be merging something very similar to this PR tomorrow.

**Comment by cgewecke** [comment]
@area Cool - if this is better on a branch you can edit at will just let me know and I'll close this and make one in your repo.

**Pull request merged**
